name: Legacy (disabled)

# This workflow has been superseded by ci.yml and deploy.yml.
# Kept for history; manual-only with a no-op job to avoid duplicate triggers.
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deprecated workflow. Use CI or Deploy workflows."
